variables:
  PROJECT_NAME: "manudomo3-front"

stages:
  - build
  - sonar
  - package

build:
  image: node:latest
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - node_modules
      - build

sonar:
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [ "" ]
  stage: sonar
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner -Dsonar.host.url=$SONAR_HOST -Dsonar.token=$SONAR_TOKEN -Dsonar.projectKey=$PROJECT_NAME -Dsonar.sources=src

package:
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "$CI_REGISTRY/$PROJECT_NAME:$CI_COMMIT_TAG"
  rules:
    - if: $CI_COMMIT_TAG
